### ISSUE TITLE
Autoupdate and download all files of bookmark list threads automaticaly

### ISSUE THREAD

**Issue by GordonFreeman86** [miku-nyan/Overchan-Android#54] opened 2015-11-10 11:15 UTC
Hi, i would be perfect in my case for this app to have the capability to download all the files of the bookmarked threads automaticaly all at once and when the autoupdate its enable, download the new files too. 

Thanks in advance, i love this app. 

PD: sorry my english.

**Comment by PwnicornDev** [comment] 2015-11-12 19:00
Duplicate of #37 ?

**Comment by miku-nyan** [comment] 2015-11-24 20:29
#37 and #56

**Closed as completed by miku-nyan** 2015-11-24 20:29 UTC
